" Vim Configuration for JavaScript, TypeScript, Shell
" Compatible with tokyonight theme, Zsh, Ghostty on Mac

" --- Basic Settings ---
set clipboard=unnamed         " Sync with System Clipboard
set nocompatible              " Modern Vim, not Vi
syntax enable                 " Enable syntax highlighting
syntax on                     " Turn on syntax highlighting set termguicolors             " Enable true colors support
set number                    " Show line numbers
set cursorline                " Highlight current line
set showmatch                 " Highlight matching brackets
set incsearch                 " Incremental search
set hlsearch                  " Highlight search results
set ignorecase                " Case insensitive search
set smartcase                 " Unless search contains uppercase
set autoindent                " Auto-indent new lines
set smartindent               " Smart indent
set expandtab                 " Use spaces instead of tabs
set tabstop=2                 " 2 spaces for a tab
set shiftwidth=2              " 2 spaces for indentation
set softtabstop=2             " 2 spaces when pressing Tab
set scrolloff=5               " Keep 5 lines visible when scrolling
set hidden                    " Allow unsaved buffers
set wildmenu                  " Command line completion
set wildmode=list:longest     " Command line completion mode
set backspace=indent,eol,start " Modern backspace behavior
set ruler                     " Show position in file
set showcmd                   " Show command being typed
set laststatus=2              " Always show status line
set signcolumn=yes            " Always show sign column

" --- Theme Configuration ---
" Theme will be set after plugin installation
" Don't set colorscheme until plugins are loaded

" --- FileType Specific Settings ---
" JavaScript
autocmd FileType javascript setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType javascript.jsx setlocal tabstop=2 softtabstop=2 shiftwidth=2

" TypeScript
autocmd FileType typescript setlocal tabstop=2 softtabstop=2 shiftwidth=2
autocmd FileType typescript.tsx setlocal tabstop=2 softtabstop=2 shiftwidth=2

" Shell
autocmd FileType sh setlocal tabstop=2 softtabstop=2 shiftwidth=2

" --- Key Mappings ---
" Leader key
let mapleader = " "

" Quick save
nnoremap <Leader>w :w<CR>

" Quick quit
nnoremap <Leader>q :q<CR>

" Toggle search highlight
nnoremap <Leader>h :set hlsearch!<CR>

" Buffer navigation
nnoremap <Leader>bn :bnext<CR>
nnoremap <Leader>bp :bprevious<CR>
nnoremap <Leader>bd :bdelete<CR>

" Shift+K to insert linebreak before current position
nnoremap K i<CR><Esc>

" Map 'jj' to escape in insert mode
inoremap jj <Esc>

" --- Plugin Management (vim-plug) ---
" If vim-plug is not installed, install it automatically
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins - Make sure to run :PlugInstall after saving this file
call plug#begin('~/.vim/plugged')

" Color scheme
Plug 'ghifarit53/tokyonight-vim'

" Syntax highlighting enhancements
Plug 'sheerun/vim-polyglot'              " Language pack
Plug 'pangloss/vim-javascript'           " JavaScript support
Plug 'leafgarland/typescript-vim'        " TypeScript syntax
Plug 'peitalin/vim-jsx-typescript'       " TypeScript JSX support
Plug 'styled-components/vim-styled-components', { 'branch': 'main' }

" Status line
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" File explorer and finder
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Git integration
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Code completion
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Code snippets
Plug 'honza/vim-snippets'

" Auto pairs for brackets, quotes, etc.
Plug 'jiangmiao/auto-pairs'

" Better commenting
Plug 'tpope/vim-commentary'

" EditorConfig support
Plug 'editorconfig/editorconfig-vim'

" Indentation guides
Plug 'Yggdroot/indentLine'

call plug#end()

" --- Plugin Settings ---
" Color scheme - applied after plugins are loaded
colorscheme tokyonight
let g:tokyonight_style = 'night'
let g:tokyonight_enable_italic = 1
let g:tokyonight_transparent_background = 1  " Enable transparency support

" Ensure terminal transparency is maintained
highlight Normal ctermbg=NONE guibg=NONE
highlight NonText ctermbg=NONE guibg=NONE
highlight LineNr ctermbg=NONE guibg=NONE
highlight SignColumn ctermbg=NONE guibg=NONE
highlight EndOfBuffer ctermbg=NONE guibg=NONE

" NERDTree
nnoremap <Leader>n :NERDTreeToggle<CR>
let NERDTreeShowHidden=1

" FZF
nnoremap <Leader>f :Files<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>g :Rg<CR>

" Airline
let g:airline_theme = 'tokyonight'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" CoC
" Use Tab for trigger completion
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" GoTo code navigation
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" IndentLine
let g:indentLine_char = '│'
let g:indentLine_color_gui = '#3b4261'

" --- Terminal Settings ---
" Better terminal support for Ghostty
if &term =~ "xterm" || &term =~ "screen" || &term =~ "kitty" || &term =~ "alacritty"
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

" --- CoC Extensions Setup ---
" Run after installing CoC
" :CocInstall coc-tsserver coc-json coc-html coc-css coc-prettier coc-eslint
